Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -7,7 +7,7 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-18.04
 
     steps:
       - name: Checkout repository
@@ -101,6 +101,15 @@ EOF
             echo "OK: log file exists"
           fi
 
+      - name: Check log file not empty
+        run: |
+          if [ ! -s test.log ]; then
+            echo "ERROR: log file is empty"
+            exit 1
+          else
+            echo "OK: log file has content"
+          fi
+
       # =========================
       # ARTIFACT
       # =========================
@@ -108,6 +117,6 @@ EOF
         uses: actions/upload-artifact@v4
         with:
           name: tg-bot
-          path: |
-            tg-bot
-            libcjson.so*
+          path:
+            - tg-bot
+            - libcjson.so*
